services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot:/var/www/certbot
  #    depends_on:
  #      - app

  #  certbot:
  #    image: certbot/certbot:latest
  #    command: certonly --webroot --webroot-path=/var/www/certbot --email sth9057@gmail.com  --agree-tos --no-eff-email -d i13a509.p.ssafy.io
  #    volumes:
  #      - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/logs:/var/log/letsencrypt
  #      - ./nginx/certbot:/var/www/certbot

  app:
    build:
      context: ./repo/backend
    image: tmi-app-image:latest
    container_name: spring-app
    ports:
      - "8080:8080"
        #    depends_on:
      # - redis
    volumes:
      - ./images:/app/images

  jenkins:
    build:
      context: ./jenkins
    image: tmi-jenkins:latest
    environment:
      - TZ=Asia/Seoul
    container_name: jenkins
    ports:
      - "8090:8080"       # Jenkins는 내부 포트 8080을 외부 8090에 매핑
      - "50000:50000"     # 에이전트 커넥션 포트
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home  # Jenkins 데이터 유지
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins에서 Docker 명령 사용 가능하게
      - ./frontend:/frontend
      - /home/ubuntu/tmi/docker-compose.yml:/docker-compose.yml:ro
    #    depends_on:
    #      - app
    networks:
      - default
