events {
        # Nginx worker 프로세스가 열 수 있는 최대 동시 연결 수 설정
        worker_connections 1024;
    }

http {
    # 프론트 코드를 text/plain이 아닌 js 파일로 읽도록 타입이 선언된 config include
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # 백엔드 서버 그룹을 정의하는 블록 - 로드 밸런싱이나 프록시 설정에 사용
    # 지금은 1개의 서버밖에 없지만 언젠가 늘어날 예정
    upstream spring_backend {
        server spring-app:8080 max_fails=3 fail_timeout=10s;
    }
    # 80 포트를 수신하는 블록
    server {
        listen 80;
        server_name i13a509.p.ssafy.io;

        # certbot 인증용 경로는 로컬 디렉토리로 직접 연결
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }

        # 나머지 요청은 443으로 리디렉션
        location / {
            return 308 https://$host$request_uri;
        }
    }

    # 443 포트를 수신하는 블록
    server {
        listen 443 ssl;
        server_name i13a509.p.ssafy.io;

        # 볼륨 마운트된 곳에서 Certbot의 pem 파일을 가져온 상태
        ssl_certificate     /etc/letsencrypt/live/i13a509.p.ssafy.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/i13a509.p.ssafy.io/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }

        # API 요청의 경우 도메인 뒤 /api가 붙으므로, /api가 포함된 경로는 해당 블록에서 처리
        location /api/ {
             proxy_pass http://spring_backend;
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;

             proxy_connect_timeout 2s; # spring 서버와 TCP 연결을 시도할 때 시간 제한
             proxy_read_timeout 5s; # 응답 데이터를 읽는 시간 제한
             # 다른 서버로 자동 재시도 - 현재는 서버가 1개밖에 없음
             proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

        # 실제 페이지 방문의 경우 도메인 뒤 아무것도 안붙으므로 /가 포함된 경로는 해당 블록에서 처리
        location / {
             root /usr/share/nginx/html;
             index index.html;
             try_files $uri $uri/ /index.html;
        }
    }
}
