events {
   worker_connections 1024;
}

http {
    include		/etc/nginx/mime.types;
    default_type	application/octet-stream;

    client_max_body_size 20M;
    upstream spring_backend {
	server spring-app:8080 max_fails=3 fail_timeout=10s;
    }

#    upstream spring_backend_v2 {
#	server spring-app-v2:8080 max_fails=3 fail_timeout=10s;
#    }

    server {
        listen 80;
        server_name i13a509.p.ssafy.io;

        # certbot 인증용 경로는 로컬 디렉토리로 직접 연결
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
	    try_files $uri =404;
        }


        # 나머지 요청은 443으로 리디렉션
        location / {
            return 308 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name i13a509.p.ssafy.io;

	ssl_certificate     /etc/letsencrypt/live/i13a509.p.ssafy.io/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/i13a509.p.ssafy.io/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

	location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }

    	location /api/subscribe { # SSE를 사용하는 특정 경로
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Connection '';
            proxy_pass http://spring-app:8080/api/subscribe;
        }

#    	location ^~ /api/v2/ {
#	    proxy_pass http://spring_backend_v2;
#
#            proxy_set_header Host $host;
#            proxy_set_header X-Real-IP $remote_addr;
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header X-Forwarded-Proto $scheme;
#
#            proxy_connect_timeout 2s;
#            proxy_read_timeout 60s;
#            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
#	}

	location /api/ {
     	     proxy_pass http://spring_backend;
	     proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
	     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	     proxy_set_header X-Forwarded-Proto $scheme;
	     proxy_connect_timeout 2s;
	     proxy_read_timeout 60s;
             proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }

 	location /login/oauth2/code/ {
            proxy_pass              http://spring_backend;
            proxy_set_header        Host              $host;
            proxy_set_header        X-Real-IP         $remote_addr;
            proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
        }

	location / {
	     root /usr/share/nginx/html;
	     index index.html;
	     try_files $uri $uri/ /index.html;
	}
    }
}
